sudo: required
language: python

services:
  - docker
cache: pip

notifications:
  email:
    - pki-devel@redhat.com
  on_success: change
  on_failure: change

env:
  - BASE_IMAGE_VERSION=29 GITHUB_BRANCH=DOGTAG_10_6_BRANCH
  - IMAGE=registry.fedoraproject.org/fedora:29 GITHUB_BRANCH=v10.7
  - IMAGE=registry.fedoraproject.org/fedora:30 GITHUB_BRANCH=v10.7
  - IMAGE=registry.fedoraproject.org/fedora:30
  - IMAGE=registry.fedoraproject.org/fedora:31

before_install:
  # You need to set local `gloabl_variables` before you can clone
  - set -a && source global_variables
  # Clone the master if $GITHUB_BRANCH is unset, else clone the specified branch
  - if [  -z "$GITHUB_BRANCH" ]; then git clone ${GITHUB_REPO}; else git clone -b ${GITHUB_BRANCH} ${GITHUB_REPO}; fi
  - set -a && source pki/travis/global_variables
  - touch ${LOGS}

install:
  - pki/travis/builder-init.sh
  - docker exec -it ${CONTAINER} rm -rf /var/cache/dnf/metadata_lock.pid
  - docker exec -it ${CONTAINER} dnf install -y dnf-plugins-core
  # Enable automated COPR repo
  - docker exec -it ${CONTAINER} dnf copr enable -y ${COPR_REPO}
  # Install latest IPA from official fedora/updates repo
  - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-init.sh

script:
  # Run the IPA tests
  - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-test.sh

matrix:
  fast_finish: true
  include:
    - stage: rawhide
      env: IMAGE=registry.fedoraproject.org/fedora:rawhide
    - env: DUMMY_JOB=FOR_FAST_FINISH
      before_install: true
      install: true
      script: true
      after_script: true

  allow_failures:
    - stage: rawhide
    - env: IMAGE=registry.fedoraproject.org/fedora:rawhide

after_script:
  - cat ${LOGS}
  - docker kill ${CONTAINER}
  - docker rm ${CONTAINER}
