sudo: required
language: python

services:
  - docker
cache: pip

notifications:
  email:
    - pki-devel@redhat.com
  on_success: change
  on_failure: always

jobs:
  include:
    - stage: PKI Nightly COPR Build
      env:
        - TASK="pki-nightly"
        - IMAGE="registry.fedoraproject.org/fedora:28"
        - GITHUB_REPO="https://github.com/dogtagpki/pki.git"
        - PKI_VERSION=10.6
        - COPR_REPO="@pki/${PKI_VERSION}-nightly"
      before_install:
        # Pull the corresponding Docker image and start the container
        - docker pull ${IMAGE}
        - >
          docker run
          --detach
          --name=${TASK}
          --privileged
          -e BUILDUSER_UID=$(id -u)
          -e BUILDUSER_GID=$(id -g)
          -e COPR_API="${COPR_API}"
          -e COPR_REPO="${COPR_REPO}"
          -e TRAVIS=${TRAVIS}
          -e TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
          -v $(pwd):/tmp
          -ti
          ${IMAGE}
      
      install:
        # Install required packages inside container
        - docker exec -it ${TASK} dnf install -y git dnf-plugins-core rpm-build copr-cli
        - docker exec -it ${TASK} dnf copr enable -y @pki/${PKI_VERSION}
        - docker exec -it ${TASK} dnf -y update

      before_script:
        # Clone upstream PKI repo from github
        - docker exec -it ${TASK} bash -c 'mkdir -p ~/.config/ && echo -e $COPR_API > ~/.config/copr'
        - docker exec -it ${TASK} git clone ${GITHUB_REPO} /pki/
      script:
        # Generate SRPM
        - travis_wait 20 ./buildCOPR.sh
        - docker exec -it ${TASK} ls /packages/SRPMS/

      after_script:
        # Clean the COPR repo for builds > 7 days
        - docker exec -it ${TASK} /tmp/pki-copr-cleaner.py

    - stage: IPA Nightly Test
      env:
        - TASK="IPA test on F27"
        - BASE_IMAGE_VERSION=27
        - GITHUB_REPO="https://github.com/dogtagpki/pki.git"

      before_install:  
        - git clone ${GITHUB_REPO}
        - set -a && source pki/travis/global_variables
        - touch ${LOGS}

      install:
        - pki/travis/builder-init.sh
        - docker exec -it ${CONTAINER} dnf install -y dnf-plugins-core
        # Enable nightly COPR repo
        - docker exec -it ${CONTAINER} dnf copr enable -y @pki/${PKI_VERSION}-nightly
        # Install latest IPA from official fedora/updates repo
        - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-init.sh

      script:
        # Run the IPA tests
        - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-test.sh

      after_script:
        - cat ${LOGS}
        - docker kill ${CONTAINER}
        - docker rm ${CONTAINER}

    - env:
        - TASK="IPA test on F28"
        - BASE_IMAGE_VERSION=28
        - GITHUB_REPO="https://github.com/dogtagpki/pki.git"

      before_install:  
        - git clone ${GITHUB_REPO}
        - set -a && source pki/travis/global_variables
        - touch ${LOGS}

      install:
        - pki/travis/builder-init.sh
        - docker exec -it ${CONTAINER} dnf install -y dnf-plugins-core
        # Enable nightly COPR repo
        - docker exec -it ${CONTAINER} dnf copr enable -y @pki/${PKI_VERSION}-nightly
        # Install latest IPA from official fedora/updates repo
        - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-init.sh

      script:
        # Run the IPA tests
        - docker exec -it ${CONTAINER} ${BUILDDIR}/pki/pki/travis/ipa-test.sh

      after_script:
        - cat ${LOGS}
        - docker kill ${CONTAINER}
        - docker rm ${CONTAINER}
